steps:
- name: 'blang/latex:ctanfull'
  args: ['bash', '-c', 'set -x; rm -rf /usr/local/texlive/2017/texmf-dist/metapost/metauml; ln -svf $(pwd)/src /usr/local/texlive/2017/texmf-dist/metapost/metauml; ls -l /usr/local/texlive/2017/texmf-dist/metapost/metauml; make release; make release-tgz']
  env:
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'TAG_NAME=$TAG_NAME'
  - 'REVISION_ID=$REVISION_ID'

artifacts:
  objects:
    location: 'gs://metauml'
    paths: ['dist/archive/metauml-$TAG_NAME-$REVISION_ID.tgz']
